// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddPostalCodeTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addPostalCode() {
    driver.get("https://www.amazon.ca/?tag=hydcaabkg-20&hvadid=317549713819&hvpos=&hvnetw=g&hvrand=1589306179093878986&hvpone=&hvptwo=&hvqmt=e&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9001318&hvtargid=kwd-13273016&ref=pd_sl_7na9ri0ehg_e&hydadcr=20060_10818753&gclid=CjwKCAjw_MqgBhAGEiwAnYOAelEot07uEYml93LVTkpgXAgpnop9sf18nj3U9iU5OPx7Yprr_u341xoCsHsQAvD_BwE");
    driver.manage().window().setSize(new Dimension(1512, 944));
    driver.findElement(By.id("glow-ingress-line2")).click();
    driver.findElement(By.id("GLUXZipUpdateInput_0")).click();
    driver.findElement(By.id("GLUXZipUpdateInput_0")).sendKeys("T#A");
    driver.findElement(By.id("GLUXZipUpdateInput_0")).sendKeys("T3A");
    driver.findElement(By.id("GLUXZipUpdateInput_1")).sendKeys("3V9");
    driver.findElement(By.cssSelector("#GLUXZipUpdate .a-button-input")).click();
  }
}
