// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GiftCardCheckoutTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void giftCardCheckout() {
    driver.get("https://www.amazon.com/");
    driver.manage().window().setSize(new Dimension(978, 824));
    driver.findElement(By.linkText("Gift Cards")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("See options")));
    }
    driver.findElement(By.linkText("See options")).click();
    driver.findElement(By.id("gc-order-form-recipients")).click();
    driver.findElement(By.id("gc-order-form-recipients")).sendKeys("fakeemail@gmail.com");
    driver.findElement(By.id("gc-order-form-date-val")).click();
    driver.findElement(By.linkText("21")).click();
    driver.findElement(By.id("gc-buy-box-atc")).click();
    driver.findElement(By.name("proceedToRetailCheckout")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".a-column > .a-color-state"));
      assert(elements.size() > 0);
    }
  }
}
